# Generated by Django 4.2.16 on 2025-05-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_alter_savingoptions_fin_prdt_cd'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saving',
            field=models.ManyToManyField(blank=True, related_name='joined2', to='deposits.savingproducts'),
        ),
    ]
